version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
  backend:
    build: ./backend
    ports:
      - "8081:8080" # Map port 8081 on the host to port 8080 in the container
